"""telegram-only auth: roles, refresh-token families, no passwords

Phase 1 of the Mini App rework (docs/DECISIONS.md D-10, D-14, D-30).

Written by hand rather than autogenerated because two of the three changes need data moved, not
just columns altered: `is_admin` has to become a role before it is dropped, and every existing
refresh token needs a family before the column can be NOT NULL.

This is an incremental migration on the existing chain, not the clean baseline D-100 calls for.
That collapse happens once, in Phase 2, when the rest of the schema changes land — collapsing
twice would mean rewriting the same baseline twice.

Revision ID: a1c7f3e29b40
Revises: 1974a8991ef0
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a1c7f3e29b40"
down_revision: Union[str, None] = "1974a8991ef0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Labels are the enum *member names*, not their values: SQLAlchemy's `Enum(PyEnum)` persists
# `.name` by default, and every existing type in this schema (language, gender, meal_type, ...)
# was created that way. Matching the convention matters more than the aesthetics — a lowercase
# type here would fail at runtime with "invalid input value for enum user_role".
USER_ROLE = postgresql.ENUM("USER", "TRAINER", "ADMIN", "SUPER_ADMIN", name="user_role")


def upgrade() -> None:
    bind = op.get_bind()
    USER_ROLE.create(bind, checkfirst=True)

    # --- users: is_admin -> role, and passwords out entirely -------------------------------
    op.add_column(
        "users",
        sa.Column("role", USER_ROLE, nullable=False, server_default="USER"),
    )
    # Anyone who was an admin under the boolean becomes `admin`, not `super_admin`: only the
    # bootstrap list (D-32) mints super admins, and inferring one here would silently hand out
    # role-granting power that nobody explicitly assigned.
    op.execute("UPDATE users SET role = 'ADMIN' WHERE is_admin = true")
    op.drop_column("users", "is_admin")
    op.drop_column("users", "password_hash")

    # --- refresh_tokens: families, so a stolen token can revoke its whole chain -------------
    op.add_column("refresh_tokens", sa.Column("family_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column("refresh_tokens", sa.Column("replaced_by_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column("refresh_tokens", sa.Column("revoked_reason", sa.String(length=50), nullable=True))
    # Existing tokens have no chain, so each becomes its own family of one. That is the honest
    # reading: nothing is known to have been rotated from anything else.
    op.execute("UPDATE refresh_tokens SET family_id = id WHERE family_id IS NULL")
    op.alter_column("refresh_tokens", "family_id", nullable=False)
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"])


def downgrade() -> None:
    op.drop_index("ix_refresh_tokens_family_id", table_name="refresh_tokens")
    op.drop_column("refresh_tokens", "revoked_reason")
    op.drop_column("refresh_tokens", "replaced_by_id")
    op.drop_column("refresh_tokens", "family_id")

    # password_hash comes back empty: the hashes are gone and cannot be reconstructed, so a
    # downgrade restores the column's shape, never the ability to log in with a password.
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.execute("UPDATE users SET is_admin = true WHERE role IN ('ADMIN', 'SUPER_ADMIN')")
    op.drop_column("users", "role")
    USER_ROLE.drop(op.get_bind(), checkfirst=True)
